# Generated by Django 4.1 on 2022-09-27 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listtodo',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='listtodo',
            name='title',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
