# Generated by Django 4.1 on 2022-09-20 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mywatchlist', '0002_rename_harga_barang_mywatchlist_rating_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mywatchlist',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
