# Generated by Django 4.1 on 2022-09-21 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mywatchlist', '0003_alter_mywatchlist_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mywatchlist',
            name='rating',
            field=models.CharField(max_length=140, null=True),
        ),
        migrations.AlterField(
            model_name='mywatchlist',
            name='title',
            field=models.CharField(max_length=140, null=True),
        ),
    ]
